### ISSUE TITLE
Not really an issue, just a question about how to build a cluster with docker image alexmerced/spark35nb:latest

### ISSUE THREAD

**Issue by ericlxbgit** [developer-advocacy-dremio/quick-guides-from-dremio#6]
Hi 
I am following the dremio instruction to do some testing.
https://www.dremio.com/blog/hands-on-with-apache-iceberg-nessie-dremio-apache-spark/

it uses the following section to build a single node spark cluster. How can I use the image "alexmerced/spark35nb:latest" to build a cluster with multiple nodes? 
It will be great if you can give me an example or some guide!
Thanks
waynelxb

  ```
spark:
    platform: linux/x86_64
    image: alexmerced/spark35nb:latest
    ports: 
      - 8080:8080    # Master Web UI
      - 7077:7077    # Master Port for job submissions
      - 8081:8081    # Worker Web UI
      - 4040-4045:4040-4045  # Additional Spark job UI ports for more jobs
      - 18080:18080  # Spark History Server
      - 8888:8888    # Jupyter Notebook
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin  # Minio username
      - AWS_SECRET_ACCESS_KEY=password  # Minio password
      - SPARK_MASTER_HOST=spark
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/tmp/spark-events
      - SPARK_HOME=/opt/spark  # Set SPARK_HOME explicitly
    volumes:
      - ./notebook-seed:/workspace/seed-data  # Volume for seeding data into the container
    container_name: spark
    entrypoint: >
      /bin/bash -c "
      /opt/spark/sbin/start-master.sh && \
      /opt/spark/sbin/start-worker.sh spark://$(hostname):7077 && \
      mkdir -p /tmp/spark-events && \
      start-history-server.sh && \
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' && \
      tail -f /dev/null
      "
    networks:
      intro-network:``



  **# I created the following section for worker node
  # then run "docker-compose up -d --scale spark-worker=2" 
  # although, the work containers start, they are not shown on Spark UI.
  # It will be great if you can show me the right way to use the image for worker containers** 

  spark-worker:
    platform: linux/x86_64
    image: alexmerced/spark35nb:latest
    ports: 
      - "8081-8099:8080"
      - "7078-7085:7000"
    depends_on:
      - spark
    environment:
      - SPARK_MASTER=spark://spark:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
    entrypoint:
      - "bash" 
      - "-c"
      - "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    volumes:
      - ./target:/opt/spark-apps
      - ./conf/worker:/conf
    networks:
      intro-network:

```
